{% set name = "pywbt" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pywbt-{{ version }}.tar.gz
  sha256: 1d582908e2849f13004dccd21e9d5cd003c964d9813fe46356f02762eb2d1b3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >=3.9

test:
  imports:
    - pywbt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pywbt
  summary: A lightweight Python wrapper for WhiteboxTools command-line interface
  license: MIT
  license_file: LICENSE
  doc_url: https://pywbt.readthedocs.io

extra:
  recipe-maintainers:
    - cheginit
